### ISSUE TITLE
[FEAT] Reminders layout improvements

### ISSUE THREAD

**Issue by fschein** [sws2apps/organized-app#3144]
**Is your feature request related to a problem? Please describe.**
When the end-of-month reminder popup for submitting a report appears, the only available option is "Remind Me Tomorrow." This can be frustrating for users who want to submit their report immediately but need to navigate manually to the submission screen.

**Describe the solution you'd like**
Add a "Send Report Now" option to the popup, which would open the report submission screen with the current month pre-selected, allowing the user to fill out and submit their report directly. Additionally, allow users to dismiss the reminder by tapping outside of the popup, which would close it and schedule the next notification for the 5th of the month as the deadline.

![image](https://github.com/user-attachments/assets/c35dc9f0-9e1c-4466-b61e-c07dda363910)

Additionally, it would be user-friendly to allow dismissing the reminder by tapping outside of the popup. This action would close the reminder and automatically schedule the next notification for the final deadline, which is the 5th of the current month.

**Describe alternatives you've considered**

- Allowing users to configure reminders in the profile page to appear only on specific days, such as the deadline date.

**Additional context**
This feature would enhance user convenience by providing immediate access to the submission screen and greater flexibility in handling reminders.

**Comment by ux-git** [comment]
Thanks for the great idea @fschein. I find it useful! Even though the notification is clickable with redirect to the report page, it can be improved to be more clean and intuitive.

• Since user might see multiple notifications (about different reports from different pages) at the same time, we can add a separate button for each notification. An arrow can work quite well to give an idea that you as user will be redirected to the corresponding page, but not submit the report right away after clicking the button. 

• Also, making each separate notification clickable (not just the icon) is already implemented and it's great, but to visually inform user about this functionality we can also show the hover state with the semi-transparent white color applied while hovering.

• Regarding the close functionality. Of course, we want publishers to submit reports in time instead of postponing it all the time, but adding another "Last chance" notification one day before the deadline even if the notification was closed is a nice idea to me. We can even add close button to make the closing more natural (clicking outside may be an accident).

<img width="845" alt="Bildschirmfoto 2024-12-04 um 10 01 42" src="https://github.com/user-attachments/assets/c30391d6-9474-4d8a-ae02-f84bfda2c591">

 @rhahao what do you think about all his?

**Comment by rhahao** [comment]
Thank you @fschein and @ux-git

1. I agree with the proposed solution to include an icon indicator + hover state to clearly show to the users that some of these items are clickable.

2. About closing the notification, I agree with the close icon too. But my question is: do we still really need the remind me tomorrow button in that case? Since I believe the close icon will do the same action too. Let’s make these two (or 1 if the other button is no longer needed) the way to close it. As said above, clicking outside will certainly be an accident. Also, adding the option to remind only on the 5th or 6th of the month is a great idea that we can add in the user profile.

Thanks.

**Comment by ux-git** [comment]
> do we still really need the remind me tomorrow button in that case?

Remind tomorrow can remind tomorrow, and closing the message fully can postpone the notification to the 5th day of the month, covering both type of users – those who need a reminder a bit later, and those who might do everything in a last minute 😄

**Comment by fschein** [comment]
Thanks @ux-git and @rhahao for the responses 😊

I didn’t know that clicking on the notification would take me to the page. It really needs to be clearer.

Some points I've notest:
- Clicking on the notification doesn’t make it disappear;
- I’ve already sent the November report, the same one it’s reminding me to send...

![Screenshot_20241204-085311_Chrome](https://github.com/user-attachments/assets/b14b4460-b0bd-4ac3-8069-ddf2941f13d0)
 Here I touched the notification, it took me to the page but didn't disappear after...

**Comment by rhahao** [comment]
> * I’ve already sent the November report, the same one it’s reminding me to send...

@fschein: this is because this notification is for the November report not the December. But now I see that the notification did not yet take into account the start date of publisher and in this case, it should not be shown at all. ☺️

**Comment by fschein** [comment]
@rhahao, why can't I see November record? Could this be a bug too?

Seems like nothing is working here:
https://github.com/user-attachments/assets/f0d4498e-6a74-4727-83f4-cc6135566521

**Comment by rhahao** [comment]
@fschein: for the November report to show, please check your person record details and make sure your publisher start date includes the month of November. This information controls which month to show in the Ministry page. 

> Seems like nothing is working here:
> https://github.com/user-attachments/assets/f0d4498e-6a74-4727-83f4-cc6135566521

I am currently working on a fix for this and it will be included within the next update.

Thanks.
