### ISSUE TITLE
[FIX] String not being translated.

### ISSUE THREAD

**Issue by fschein** [sws2apps/organized-app#3241]
### Describe the bug:

The string: [tr_hallWithName](https://crowdin.com/editor/organized/2028/en-ptbr?view=side-by-side#43964), is not being translated for any language.

### Steps to reproduce the issue:

1. Open the My assignments screen.
2. If you have an assignment with Hall A, note that the translation is not applied in any non-English language.

### Expected behavior:

Apply the translation.

### Screenshots

![image](https://github.com/user-attachments/assets/75cf012d-646f-42a8-a4f8-a0f3130ee622)

English:
![image](https://github.com/user-attachments/assets/94de0069-4c27-4dd8-9b86-d59cd004448e)

Portuguese-BR:
![image](https://github.com/user-attachments/assets/2db397ca-7909-4657-acef-7228e9ec3e5f)

Deutsch (Sometimes the assignment names won't load, occurring in multiple languages):
![image](https://github.com/user-attachments/assets/556a8067-452b-4d07-b8dd-e7b72f62b895)

### Which platform can you reproduce the bug on?

Desktop

### Your operating system:

Linux

### App version:

3.4.2

**Comment by ux-git** [comment]
> Sometimes the assignment names won't load, occurring in multiple languages

I now suppose the translated languages do not appear instantly after the switch because the meeting materials are simply not synced with jw.org. The sync happens automatically every few weeks or manually by clicking sync with jw.org button on the Meeting materials card.

It's hard to predict whether user wants to switch language forever and to another language for scheduling etc, OR it's just testing purposes for a few minutes.

@rhahao do you think it would make sense to trigger the jw.org meeting materials sync right on a language selection? This way the changes will happen in the background which will be almost unnoticeable for user in most cases. And in most other cases users will then switch back to their preferred language making the app's behavior back to normal (I hope 😀). What do you think?

**Comment by mrtavor** [comment]
Hey @fschein @ux-git Regarding the missing translation key, it has been fixed in #3242
