### ISSUE TITLE
[Iloko] - New language request

### ISSUE THREAD

**Issue by kentestaccount** [sws2apps/organized-app#3248]
### Enter the jw.org url to access this language:

jw.org/ilo

### Please provide translations for the following theocratic terms in your language:

Assignment: Paset
Student (of a meeting): Estudiante
Assistant (of a student): Katulongan
Bible study: Panagadal iti Biblia
Branch office: Sanga nga opisina
Bethel: Bethel
Chairman: Tserman
Congregation: Kongregasion
Circuit overseer: Manangaywan iti sirkito
Circuit overseer visit: Bisita ti manangaywan iti sirkito
Elder: Panglakayen
Governing Body Update (video): Update Manipud iti Bagi a Manarawidwid
Kingdom Hall: Kingdom Hall
Ministerial servant: Ministerial nga adipen
Ministry: Ministerio
Meeting: Gimong
Meeting schedule: Eskediul ti Gimong
Meeting workbook: Workbook iti Gimong
Memorial: Memorial/Pananglaglagip (lit. Remembering)
Midweek meeting: Gimong iti Tengnga ti Lawas
Weekend meeting: Gimong iti Ngudo ti Lawas
Organizational Accomplishments (video): Dagiti Nagapuanan ti Organisasion
Schedule: Eskediul
Service: Serbisio
Publisher: Agibumbunannag
Prayer: Kararag
Pioneer application: _Pioneer application_
Report: Report
Reader: Parabasa
Regular pioneer: Regular Pioneer
Auxiliary pioneer: Auxiliary Pioneer
Speaker: Ispiker
Talk: Palawag
Territory: Teritoria

**Comment by ux-git** [comment]
@kentestaccount is the Ilokano language provided by Crowdin the right one in this case? 

<img width="116" alt="Bildschirmfoto 2024-12-17 um 10 56 15" src="https://github.com/user-attachments/assets/c79268d1-e1f5-44e0-8a63-97e03823e798" />

On jw.org it's listed as Iloko, but there's no this exact language on Crowdin. If it's not the correct one, we can create a custom language to allow you translsate the app anyway.

**Comment by kentestaccount** [comment]
@ux-git Yes, Iloko and Ilokano is the same.

**Comment by ux-git** [comment]
Great! Then the Crowin page with the language is already available. Expect the AI pre-tranlsations to arrive in the coming minutes. Then you'll be able to proofread them and correct if needed instead of translating everything from scratch. Thanks for your contribution!

There are also other smaller Crowdin projects that supports Organized app, namely [Meeting Schedules Parser](https://crowdin.com/project/cpe-jw-epub-parser) to fetch all the meeting materials in your language and [Notifications and Release notes project](https://crowdin.com/project/organized-miscellaneous/ilo) that allows to localize even temp notifications/notes. Feel free to check them out as well.

@rhahao could you please also import songs once you have a chance?

**Comment by kentestaccount** [comment]
hiya! any way we could update public talk themes? do you need an updated s-99 in iloko?

**Comment by ux-git** [comment]
@kentestaccount there's a dedicated Crowdin project for public talks: https://crowdin.com/project/organized-public-talks

You can edit the talk titles directly there :)

**Comment by kentestaccount** [comment]
@ux-git i've submitted a request to edit
